title: My inputs or outputs don't work as expected
hero_image: images/banner.png
description: debug-pico-hardware description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-07"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
