---
title: Mes entrées ou sorties ne fonctionnent pas comme prévu
hero_image: images/banner.png
description: Mes entrées ou sorties ne fonctionnent pas comme prévu
version: 4
listed: false
copyedit: false
last_tested: "2022-03-07"
steps:
  - title: Mes entrées ou sorties ne fonctionnent pas comme prévu
